<div class="left">
	<a href="http://claimid.com/lbolla">claimid</a> |
	<a href="http://delicious.com/lbolla">del.icio.us</a> |
	<a href="http://flavors.me/lbolla">flavors.me</a> |
	<a href="http://www.flickr.com/photos/lbolla">flickr</a> |
	<a href="http://www.github.com/lbolla">github</a> |
	<a href="http://www.google.com/profiles/lbolla">google</a> |
	<a href="http://www.last.fm/user/lbolla">last.fm</a> |
	<a href="http://www.linkedin.com/in/lorenzobolla">linkedin</a> |
	<a href="http://sourceforge.net/users/lbolla">sourceforge</a> |
	<a href="http://lbolla.wordpress.com">wordpress</a>
</div>

<div class="right">
	<span class="doNotDisplay">Related sites:</span>
	<a href="/sitemap">site map</a> |
	<a href="/_users/login">login</a> |
	<!-- AddThis Button BEGIN -->
	<a class="addthis_button" href="http://addthis.com/bookmark.php?v=250&amp;username=lbolla"><img src="http://s7.addthis.com/static/btn/v2/lg-share-en.gif" width="125" height="16" alt="Bookmark and Share" style="border:0"/></a><script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#username=lbolla"></script>
	<!-- AddThis Button END -->
</div>

