baseURL = 'https://lbolla.info/'
locale = 'en-us'
title = 'Lorenzo Bolla'
theme = ['hugo-bearblog']

[markup.goldmark.renderer]
unsafe = true

[caches.images]
dir = ':cacheDir/images'

[params]
favicon = "favicon.ico"
