[build.environment]
GO_VERSION = "1.26.4"
HUGO_VERSION = "0.164.0"
NODE_VERSION = "24.18.0"
TZ = "Europe/Rome"

[build]
publish = "public"
command = """\
  git config --global core.quotepath false && \
  hugo build --gc --minify --baseURL "${URL}"
  """
