<div class="left">
	<a href="http://claimid.com/lbolla">claimid</a> |
	<a href="http://delicious.com/lbolla">del.icio.us</a> |
	<a href="http://flavors.me/lbolla">flavors.me</a> |
	<a href="http://www.flickr.com/photos/lbolla">flickr</a> |
	<a href="http://www.github.com/lbolla">github</a> |
	<a href="http://www.google.com/profiles/lbolla">google</a> |
	<a href="http://www.last.fm/user/lbolla">last.fm</a> |
	<a href="http://www.linkedin.com/in/lorenzobolla">linkedin</a> |
	<a href="http://lbolla.wordpress.com">wordpress</a>
</div>

<div class="right">
	<span class="doNotDisplay">Related sites:</span>
	<a href="/sitemap">site map</a> |
	<a href="/_users/login">login</a>
</div>
