#+TITLE: Lorenzo Bolla - Curriculum Vitæ
#+AUTHOR:
#+DATE:
#+OPTIONS: toc:nil num:0

[[mailto:contact@lbolla.info][EMail]] | [[https://github.com/lbolla/][GitHub]] | [[https://stackoverflow.com/users/1063605/lbolla][StackOverflow]] | [[https://www.linkedin.com/in/lorenzobolla][LinkedIn]] | [[https://lbolla.info][Website]]

/Less detailed CV available [[https://lbolla.info/cv-short][here]]./

* _Profile_

I am an experienced Software Engineer with a background in research Physics.

I graduated as Telecommunication Engineer in the field of classical optics and
telecommunications algorithms. I achieved a Doctorate Degree on Numerical
Methods applied to Physical problems.

I have 15+ years of experience in software engineering. I worked on projects
spanning highly scalable web applications, numerical intensive simulations and
massively parallel data analysis. I have 3+ years of experience in DevOps,
especially with [[https://www.docker.com/][Docker]] and [[https://kubernetes.io/][Kubernetes]].

Fluent in [[https://www.python.org/][Python]], [[https://www.rust-lang.org/en-US/][Rust]], Javascript, HTML, CSS. Familiar with C/C++ (using both
STL and Boost libraries), Java, Fortran and Matlab. Interested in other
programming languages, like [[https://www.erlang.org/][Erlang]], [[https://www.haskell.org/][Haskell]], Lisp and [[https://golang.org/][Go]].

Experienced with many different libraries and frameworks: Tornado, CherryPy,
Numpy, Pandas, Disco, JQuery, ExtJS, git, MySQL, sqlite, MongoDB, nginx, and
many more. Experience in database design, especially using [[https://www.postgresql.org/][Postgresql]].

Lifelong Linux user and open-source contributor.

Logical thinker, able to provide effective solutions to solve difficult
problems.

Great team-player & fun attitude, competent time manager, very dependable under
pressure and passionately dedicated to the task. Experienced remote worker.

* _Experience_
** [[https://www.roche.com/][Roche]], Linux Software and Hardware Expert, Dec 2020 -- now

Design and implement operating system and infrastructure for diagnostic medical
instruments. Deep experience with Debian-based operating system, packaging and
software practices. Broad experience with DevOps practices, writing CI
pipelines, testing across various hardware, etc.

** [[https://yougov.com/][YouGov]], Senior Software Developer, Aug 2013 -- Dec 2020

Design and implement scalable analysis software for market research analysis
using _Python_, _Rust_, _Cython_, _MongoDB_, _PostgreSQL_. Development of an
in-memory column-oriented DB to efficiently store and query tabular data. Lead
junior developers, ensure best practices and code quality, automate deployments
and continuous delivery.

** [[https://yougov.com/][YouGov]], Director of DevOps, Aug 2015 -- Jun 2020

Lead the DevOps team, to improve automation of development
processes. Manage the migration from legacy to state-of-the-art
infrastructure, based on _GitLabCI_, _Docker_ and _Kubernetes_.
Responsibilities include soliciting project ideas, setting priorities
and scheduling projects. 25% time position dedicated to this role;
remaining 75% Lead Python Developer.

** [[http://www.companiesintheuk.co.uk/ltd/raid-research-services-llp][RAID Research Services LLP]], Senior Software Architect, May 2012 -- Aug 2013

Design and implement scalable analysis software for finance using
mainly _Python_, _Pandas_, _MySQL_ and _ExtJS_. Implementation of an in-memory
DB to efficiently query tabular data. Parsing of unstructured data
sources and categorization using simple machine learning techniques.

** [[http://www.artirix.com/][Artirix Ltd]], Senior Software Engineer, Apr 2012 -- May 2012

Design and implementation of highly scalable web search crawlers using
_Python_ and _Twisted_.

** [[http://www.zugo.com/][Zugo Ltd]], Senior Python Developer, Apr 2011 -- Apr 2012

Develop massively scalable web applications (using _Python_, _Tornado_, _MySQL_, _MongoDB_,
_nginx_ on the back-end and _HTML_, _Javascript_, _CSS_ on the front-end). Experience
in distributed data analysis using MapReduce frameworks (mainly Disco), NoSQL
data stores (mainly _MongoDB_) and _AWS_ solutions. Some experience in browser
extension implementation (Firefox and Chrome).

** [[http://www.geneity.co.uk/][Geneity Ltd]], Software Engineer, Aug 2008 -- Apr 2011

Software engineer of high-performance E-gaming web applications (mainly working
with Betfair, Coral, Ladbrokes and others betting companies). Focus on high
performance fund transfers (maximizing the transaction per seconds supported by
the systems), application reliability (maximizing uptime), third-party
usability (implementing REST and SOAP access to web applications). Programming
languages used: _Python_ (2.5, 2.6), _C,_ PL/SQL (Oracle 10g-11) for the back-end;
_HTML_/_Javascript_ for the front-end. OS used: Linux (Debian, Suse and ArchLinux
distributions).

** [[http://www.pirelli.com/][Pirelli & C SpA]], Optical Designer, Jun 2005 -- Aug 2008

R&D in Photonic Integrated Circuits mainly based on Silicon-on-Insulator
technology (SOI-PICs). Responsible for the design of optical components for
metro and access networks, with a focus on innovative solutions. Excellent
problem solving capabilities, lateral thinking and self management. Deep
experience on efficient numerical and parallel programming (SGI Altix
hardware), using _C/C++_, _Fortran_, _Matlab_, _Python_ languages and _OpenMP_,
_MPI_, _STL_ and _Boost_ libraries. Experience in patenting.

** [[http://www.telesystem.it/][TELE System Electronic Srl]], Software Engineer, Mar 2005 -- Jun 2005

Consultant on hardware and software design for digital television broadcasting,
including theory on transmission algorithms and computer simulations of the
complete system. Experience in programming applications for set-top-boxes, in
_Java_.

** [[http://www.photond.com/][Photon Design Ltd]], Software Engineer, Apr 2003 -- Apr 2004

R&D on numerical algorithms applied to the solution of electromagnetic
problems. Very deep focus on algorithms' efficiency for computationally
intensive simulations. Theoretical studies on linear algebra problems, finite
difference and finite elements algorithms, modal expansion techniques. Deep
experience in _C/C++_ programming, both with VC++ and Borland suites (along with
STL and Boost libraries) and _Python_ as scripting language. Basics of GUI
programming.

** [[http://www.progettomantegna.it/][Progetto Mantegna]], Technical Support, May 2001 -- Apr 2003

Technical assistance in the virtual reconstruction of Mantegna's paintings in
the Ovetari's Chapel, Padua Italy. Basics of image analysis and manipulation.

* _Education_
** University of Udine - Italy, PhD, Nov 2002 -- Nov 2005

[[http://www.scribd.com/doc/19603116/LorenzoBollaPhDthesis][Thesis]] on the numerical solution Maxwell equations in periodic dielectric
devices.

** European Project, FUNFOX (Project No. 004582), Sep 2004 - Jun 2005

Research on semiconductor optoelectronic devices for metro core and access
segments in optical networks.

** European Project, PICCO (IST-1999-10361), Nov 2002 - Apr 2003

Research in Optical integrated circuits, photonic crystal planar waveguides and
wavelength dependent devices.

** University of Padova - Italy, Telecommunication Engineering, Sep 1996 - Mar 2002

* _Publications_
** Books
- [[https://www.scholars-press.com/catalog/details/store/de/book/978-3-639-51669-2/numerical-methods-for-integrated-optics?search=numerical%20methods]["Numerical Methods for Integrated Optics"]], Lorenzo Bolla, Scholar's Press, 2013, ISBN 978-3-639-51669-2
- Technical reviewer for [[http://www.packtpub.com/numpy-1-5-using-real-world-examples-beginners-guide/book]["Numpy 1.5 Beginners Guide"]], PacktPub, ISBN 1849515301
- Technical reviewer for [[http://www.packtpub.com/learning-scipy-for-numerical-and-scientific-computing/book]["Learning Scipy for Numerical and Scientific Computing"]], PacktPub, ISBN 1782161627
- Technical reviewer for [[http://www.packtpub.com/haskell-data-analysis-cookbook/book]["Haskell Data Analysis Cookbook"]], PacktPub, ISBN 1783286334
** Articles
- V. Sorianello, M. Balbi, L. Colace, G. Assanto, L. Socci, *L. Bolla*, G. Mutinati, M. Romagnoli, "Guided-wave photodetectors in Germanium on SOI optical chips", Physica E: Low-dimensional Systems and Nanostructures, [[http://dx.doi.org/10.1016/j.physe.2008.08.038][abstract]]
- M. Romagnoli, L. Socci, *L. Bolla*, et al., "Silicon Photonics in Pirelli" (invited), Proc. SPIE 2008, [[http://spie.org/app/program/index.cfm?fuseaction=addconfevent&startrow=1&date=12/31/1969&eventid=848935#848935][website]]
- T. P. Felici, D. F. G. Gallagher, *L. Bolla*, "Automatic design and optimisation of Si nanophotonics devices using finite element frequency domain solvers", Proc. SPIE Vol. 6475, 64750L, Integrated Optics: Devices, Materials, and Technologies XI, 2007, [[http://spie.org/x648.html?product_id=717509][abstract]]
- M. Kotlyar, *L. Bolla*, M. Midrio, L. O'Faolain, and T. Krauss, "Ultra-short InP-based polarisation rotator", PECS-VI International Symposium on Photonics and Electromagnetic Crystal Structures, 2005, [[http://www.cmpgroup.ameslab.gov/PECSVI/][website]]
- M. Kotlyar, *L. Bolla*, M. Midrio, L. O'Faolain, and T. Krauss, "Photonic Crystals for Polarisation Diversity Circuits", Frontier in Optics (the 89th OSA Annual Meeting), Tucson (Arizona), 2005, [[http://www.osa.org/en-us/meetings/osa_meeting_archives/][website]]
- M. Kotlyar, *L. Bolla*, M. Midrio, L. O'Faolain, and T. Krauss, "Compact polarization converter in InP-based material", Opt. Express 13, 5040-5045, 2005, [[http://www.opticsinfobase.org/abstract.cfm?URI=oe-13-13-5040][abstract]]
- *L. Bolla*, "Polarization Rotators", Technical Report, FUNFOX Project, Lausanne, Switzerland, 2005, [[http://www.iota.u-psud.fr/~funfox/][website]]
- *L. Bolla*, M. Midrio, and C. G. Someda, "Energy flow in negative index materials", Chin. Opt. Lett. 2, 428-430, 2004, [[http://www.opticsinfobase.org/abstract.cfm?URI=col-2-7-428][abstract]]
- *L. Bolla*, and T. Felici, "New discretisation scheme for frequency domain electromagnetics", PIERS 2004 Proceedings, Pisa, Italy, 2004, [[http://sun8.dsea.unipi.it/piers04_v3/][website]]
- *L. Bolla*, "Planar Generalized Yee Algorithm", Technical Report, PICCO Project, Padua, Italy, 2002, [[http://intecweb.intec.ugent.be/picco/][website]]
** Patents
Author or Co-author of [[https://www.google.com/?tbm=pts&hl=en#sclient=psy-ab&hl=en&site=&tbm=pts&source=hp&q=lorenzo+bolla&oq=lorenzo+bolla&gs_l=hp.3..0j0i10i30j0i30l2.1702.2984.0.3102.13.11.0.1.1.0.129.763.9j2.11.0...0.0.ABApNeaWOfs&pbx=1&bav=on.2,or.r_gc.r_pw.,cf.osb&fp=14d568fa9404c2ae&biw=1278&bih=945][10 international patents]] in the field of integrated
optics.
** Citations
[[https://scholar.google.co.uk/citations?hl=en&user=mHfVbDwAAAAJ&scilu=&scisig=AMstHGQAAAAAW-GM4dJr8fj_Xcq8qdlmAXKozUEfhYLn&gmla=AJsN-F7PIh8oNRvySBFFGW8OPF_URY6Sq01Np2dU272500KgmQtdDRvXvSWEaiSdogqo3KFLOSL3GohfXcKoJuZAPcJp_1P0cEQLfDUfjWiCTbtafzA73sA&sciund=13977132764972751311][List of citations from Google Scholar]]
