#+TITLE: Facile profeta

#+DATE: <2007-09-15>

Questo e' il secondo post in cui nomino Beppe Grillo: ormai e' una delle mie fonti di informazione primarie! Su [[http://www.repubblica.it/2007/09/sezioni/esteri/bombe-atomiche/bombe-atomiche/bombe-atomiche.html][repubblica.it]] di oggi e' riportata la notizia che, secondo un rapporto americano, in Italia sono presenti 90 ordigni nucleari statunitensi, conservati nelle basi militari di Aviano e Ghedi. Vale la pena ricordare che:

#+BEGIN_QUOTE
  A rigor di legge, la presenza di questi ordigni non sarebbe consentita: la legislazione la vieta espressamente dal 1990. Il nostro Paese ha inoltre sottoscritto i trattati internazionali di non proliferazione nucleare e ha dichiarato di non far parte del club atomico, con tutti gli obblighi internazionali che ne derivano.
#+END_QUOTE

Naturalmente, questa non e' propriamente una notizia. A febbraio, [[http://www.beppegrillo.it/2007/02/italia_nucleare.html#trackbacks][Grillo l'aveva gia' denunciato]]. Mi domando perche' Grillo arrivi prima di Repubblica.
