#+TITLE: Migrating away from wordpress.com

#+DATE: <2011-04-11>

Today I decided to migrate my blog from [[http://lbolla.wordpress.com][wordpress.com]] to [[https://lbolla.info/blog][my own domain]].

I did it for many reasons:

-  To be able to [[http://en.forums.wordpress.com/topic/adding-plugins?replies=8][add plugins]]
-  To be able to [[http://wordpress.org/support/topic/adding-javascript-to-page][add javascript]] to individual pages
-  To run a [[http://63222hljwcjlds6no5lczchgsg.hop.clickbank.net/][customized theme]]
-  And all the other reasons listed [[http://en.support.wordpress.com/com-vs-org/][here]]

I did not want to loose the popularity and the ranking of my original address, accumulated over the years.

Here are the steps I had to follow (if the following steps make no sense to you, [[http://a07086nbyhov3xdnzplolg3tdz.hop.clickbank.net/][this guide]] might help you):

-  Setup a new empty Wordpress blog at [[https://lbolla.info/blog][lbolla.info/blog]]
-  Exported the whole old blog as XML file (better called =WordPress eXtended     RSS= or =WXR=): simply log into the admin interface of the old blog and click =Tools > Export=
-  Imported the =WXR= file into the new empty blog by clicking =Tools >     Import= in the admin interface
-  Activate the =Site Redirect= upgrade in the old blog by clicking on =Upgrades= in the left-hand menu of the admin interface and paying a whopping 12$/year. Here is the description of this service:

#+BEGIN_QUOTE
  Do you want to move away from WordPress.com to your own self-hosted WordPress installation without losing SEO ranking and breaking links? Have you recently changed your blog address and need to move traffic to the new address? This upgrade redirects your wordpress.com blog to your new blog by performing permanent (301) redirects for all of your content.
#+END_QUOTE

All the procedure took no more than 15 minutes. Brilliant.
