#+TITLE: Qui Milano libera

#+DATE: <2007-07-19>

[youtube=http://www.youtube.com/watch?v=H--4qyu5sSY]

Un magistrato di roma ha ordinato alla guardia di finanza di chiudere il blog di questo signore ([[http://www.pieroricca.org][Piero Ricca]]), reo di [[http://uk.youtube.com/watch?v=5KbGNQwO7es][aver accusato Emilio Fede]] di occupare abusivamente le frequenze di retequattro, ed essersi beccato uno sputazzo per tutta risposta. Fortunatamente, il sito [[http://www.quimilanolibera.net][www.quimilanolibera.net]] ha deciso di ospitare i post di Piero Ricca finche' il suo blog non sara' di nuovo disponibile.

Tratto da [[http://www.quimilanolibera.net/wp-content/uploads/2007/07/rete4-abusiva-mondadori-rubata.pdf][www.quimilanolibera.net]]:

#+BEGIN_QUOTE
  Rete 4 trasmette da anni "in proroga", contro due sentenze della Corte Costituzionale. Si è salvata fino ad ora grazie ad agganci politici e decreti su misura. Le frequenze occupate abusivamente da questa emittente spettano a Europa 7 di Francesco Di Stefano, titolare dal 1999 di regolare concessione nazionale. Di Stefano attende giustizia dalla Corte Europea e ha chiesto un risarcimento di 3 miliardi di euro. Se vince, lo Stato cioé i cittadini dovranno mettere mano al portafoglio.per risarcire un abuso compiuto da Berlusconi, nel silenzio di gran parte della sinistra.
#+END_QUOTE
