#+TITLE: Useful scripts - a+/a-

#+DATE: <2012-11-02>

This is the first post of a series describing simple scripts that I wrote to ease my life as a programmer.

They are implemented in various languages (=python=, =bash=, =go=) and thought to be used in =Linux=. Some of them are "general purpose", while others are specifically designed to interface other tools I use (for example, [[http://acme.cat-v.org/][=acme=]].)

All of them tend to have the following properties:

-  Input from =stdin=, output to =stdout=, errors to =stderr=
-  Return zero on success, non-zero on failure
-  Do one thing only
-  Not too much customizable

These properties allow the scripts to remain very simple, be composable and easy to remember.

They are [[https://github.com/lbolla/cmd][available on github]]: fork & hack at will!

** a+/a-

In this post I'll describe a very simple script, [[https://github.com/lbolla/cmd/blob/master/a%2B][=a+=]], and its counterpart [[https://github.com/lbolla/cmd/blob/master/a-][=a-=]]. They are the first I wrote when I started using [[http://acme.cat-v.org/][=acme=]].

=a+= indents every line of =stdin= by 4 spaces. =a-= "de-indents" it by the same amount. The amount of spaces (4) is fixed (to resist the temptation to change it), and indentation is done with [[http://www.python.org/dev/peps/pep-0008/#tabs-or-spaces][spaces and not tabs]].

The code is trivial: it uses [[http://swtch.com/plan9port/man/man1/sed.html][=sed=]] and [[http://swtch.com/plan9port/man/man1/rc.html][=rc=]], the [[http://swtch.com/plan9port/][Plan9's shell ported to *nix]] (although, in this case, any shell would do.) Here it is:

*** a+

#+BEGIN_SRC shell
    # !/usr/bin/env rc  

    sed 's/^/ /'  
#+END_SRC

*** a-

#+BEGIN_SRC shell
    # !/usr/bin/env rc  

    sed 's/^ //'  
#+END_SRC
