#+TITLE: Wordpress to markdown

#+DATE: <2012-11-12>

Recently, I moved away from [[http://wordpress.com/][Wordpress]]. I did it primarily because [[http://john.onolan.org/ghost/][Wordpress is so much more than *just* a blogging platform]] and what I needed was just a simple way of publishing posts with embedded code, links and images. Moreover, writing blogs using Wordpress's web editor is less than ideal...

The biggest problem to solve when moving away from Wordpress is how to not lose all your posts. Luckily, Wordpress allows you to [[http://codex.wordpress.org/Tools_Export_Screen][export all your stuff in XML]], but you also need a way to import them in whatever other blogging platform you are going to use.

After some research, I decided to choose a [[http://mickgardner.com/2011/04/27/An-Introduction-To-Static-Site-Generators.html][static site generator]]. Out of all the [[http://siliconangle.com/blog/2012/03/20/5-minimalist-static-html-blog-generators-to-check-out/][available alternatives]], I picked [[http://liquidluck.readthedocs.org/en/latest/][Felix Felicis]] (aka "liquidluck"): it's written in Python, very simple to customize and extend, and with some pleasing themes. Other solutions, like [[https://github.com/mojombo/jekyll][jekyll]], [[http://publicstatic.org/][public-static]], etc. are way too "powerful" (read "complicated") for my taste.

Unfortunately, unlike other more popular alternatives, [[http://liquidluck.readthedocs.org/en/latest/][Felix Felicis]] does not come with an "importer" of Wordpress's XML file. So, I decided to [[https://github.com/lbolla/wp2md/tree/liquidluck][fork one of the existing solutions and adapt it to my needs]].

I also forked the [[https://github.com/lepture/liquidluck-theme-moment][liquid luck's default theme]] and [[https://github.com/lbolla/liquidluck-theme-moment][created my own]].

If you want to do like me, migrate away from Wordpress and use Felix Felicis as your static site generator, do the following:

1. Export your posts from Wordpress in an XML file
2. =git clone= my fork of =wp2md= and run it over the XML file
3. Manually check that all your links and posts have been properly exported: mine needed almost zero editing!
